### PR TITLE
React Query add

### PR DESCRIPTION
**Pull request by thesaikatparua**
Hi @Debduttaa,

Please merge and approve the code.

Feature Added:
1.  React Query add and modify the code.

cc: @Subhratanu @Bodhisattwa13

### CODE REVIEW

**Review by Subhratanu — APPROVED** [review]
Hi @thesaikatparua ,

As it's a major change in the flow please confirm everything is working fine, afterwards I'll merge it, instead approving now.

Thanks!

**Comment by thesaikatparua** [comment]
@Subhratanu till now everything working fine but one more thing if there internet is slow then it is taking time to load.

**Comment by Subhratanu** [comment]
Cool @thesaikatparua ,

Spinner will do that job for us , no worries!

**Comment by Subhratanu** [comment]
Hi @Debduttaa / @Bodhisattwa13 

Please revert here, if the latest changes is working fine on your system!

Cc: @thesaikatparua

**Pull request merged**
